### ISSUE TITLE
DllNotFoundException: SysFont

### ISSUE THREAD

**Issue by masak2** [imkira/unity-sysfont#1]
こんにちは

 windows7 home で開いたところ
DllNotFoundException: SysFont
SysFont.QueueTexture (System.String text, System.String fontName, Int32 fontSize, Boolean isBold, Boolean isItalic, Boolean isMultiLine, Int32 maxWidthPixels, Int32 maxHeightPixels, Int32 textureID) (at Assets/Plugins/SysFont/SysFont.cs:182)

とエラーが出て何も表示されませんでした。
しかし　build したら android で正しく表示されました。

windows editor 上では対応してないのでしょうか？

**Comment by imkira** [comment]
masak2さん
こんにちは。

はい、windowsではまだ対応していないというエラーです。
今月末までに暇な時間をみつけてwindowsを対応したいと思いますが、なんとも約束できません。

**Comment by masak2** [comment]
了解しました、
android 上で簡単に文字表示できて素晴らしいプラグインと思いました！

**Comment by GarthSmith** [comment]
This is a 2 year old issue, but I am also getting DLLNotFoundException: SysFont which is occuring from the SysFont.QueueTexture method call. Is there some resolution I can't find?

**Comment by GarthSmith** [comment]
Hello! I just saw this. This would probably explain it! Thanks!

==Quoted Text==
Limitations
    unity-sysfont is not currently supported on Windows (I have plans to support it in the near future). Keep in touch!
