### ISSUE TITLE
build on Android platform by Unity3D version 3.4.2 

### ISSUE THREAD

**Issue by olncy** [imkira/unity-sysfont#14]
I had try to build an Android application by Unity3D version 3.4.2. Then I run the program and it is work well.
But I found when I press home button go to desktop and then come back to the program, all SysFontTexture turn into black color texture. It would be solved by change text attribute and render the SysFontTexture again.

There is no problem build by Unity3D version 3.5.5.

How could I do in Unity3D version 3.4.2?

**Comment by imkira** [comment]
Sorry, I do not plan on supporting old versions of unity.
