### ISSUE TITLE
Error with the new unity version 2.1.6

### ISSUE THREAD

**Issue by eddieKayac** [imkira/unity-sysfont#4]
the new update of NGUI add somme problem
NGUI 2.1.6

Assets/SysFont/Compatibility/NGUI/Scripts/UISysFontLabel.cs(243,30): error CS0115: `UISysFontLabel.OnFill(BetterList<UnityEngine.Vector3>, BetterList<UnityEngine.Vector2>, BetterList<UnityEngine.Color>)' is marked as an override but no suitable method found to override

Changing this line of code seems to resolve the problem.

UISysFontLabel 243-244
OnFill(BetterList<Vector3> verts, BetterList<Vector2> uvs, BetterList<Color> cols)
↓
OnFill(BetterList<Vector3> verts, BetterList<Vector2> uvs, BetterList<Color32> cols)

is this the right thing to do?

**Comment by fishtopher** [comment]
I'm not sure if github tried to format the template tags as html tags, so it's not obvious what your change is, here's what I did to fix it:

``` c#
override public void OnFill(BetterList<Vector3> verts, BetterList<Vector2> uvs, BetterList<Color> cols)
```

↓

``` c#
override public void OnFill(BetterList<Vector3> verts, BetterList<Vector2> uvs, BetterList<Color32> cols)
```

i.e.  `<Color>` becomes `<Color32>`

**Comment by eddieKayac** [comment]
yes it is. 
thanks.

**Comment by imkira** [comment]
Thank you.

I have just fixed this issue and uploaded the new unity-sysfont-ngui compatibility package file.
