### ISSUE TITLE
too many draw calls!

### ISSUE THREAD

**Issue by dongxie** [imkira/unity-sysfont#5]
hi,why not improve your uisysfontlabel to draw a large atlas ,because if u use uisysfontlabel to create a sheet chinese/japanese name list,include many sysfont,that would increase drawcalls num,is it a way to combine your draw to be one altas,

**Comment by Borluse** [comment]
that would be very difficult in my opinion. this pluggins is dynamically using system font. which means it wont create such a atlas before your game is in run-time. This is because :
    1) This plugins is a way to reduce amount of textures needed in your game package. which means the size of your game. It makes no sense to create such an atlas before run-time.

```
2) If you know how many words you need, why not just create the atlases in traditional way ?

3) Or, imkira has to do a mechanism create a  full atlas of one font in run-time. which is i think a waste of time, and slows your game. 
```

btw,  If you know exactly what characters you will need in your game, it  would be probably much better to use the traditional way to create your character atlases. Leave only one or two place to use this plugins. such like the player's name. in those place, you can't predict the characters needed.

**Comment by imkira** [comment]
It is just like @Borluse said. It is not "trivial" to solve this problem during runtime and I believe there is no "best approach" using the current architecture.
Here is how the plugin works:
- For every label you have, it constructs a texture containing that label.
- Creates a 2D mesh with 4 vertices (2 triangles) with the textured mentioned above mapped into it.
- Everytime you change a label's text by saying, for instance, `label.Text = "FPS: " + fps;` the previous steps are repeated.

The reason for the high draw count is the fact that every label has its own texture and mesh, ie. they are not shared among labels.
One of the possible approaches to reducing draw count, would be to pack several labels into a single texture. The problem arises when you want to change one texture, you have to regenerate the texture (not just the current label but all the labels that the algorithm decided to include in the same texture). So if we were to do this we would need:
- a fast texture packing algorithm at runtime
- an intelligent texture aggregator, that, for instance, aggregates labels which rarely change in the same texture and textures that change too often in their own texture.

The other problem would be having to share the same mesh, if you don't want to rely on automatic batching by Unity. This would be doable if the texture problem was easily solvable, which I don't think it is at the moment.

**Comment by dongxie** [comment]
Hi, what my opinion is when some words was created by your plugins ,its best way to draw them to a bigger texture than use in separate small textures. that would cost more less draw calls.
we usually use uisysfont to display the info was loading from out of game or human name(multi languages).if we create a list of hundreds of names .when we  slide them in a scroll panel ,the performance is very slow(too many draw calls).
many chars wouldn't be changed when they were created in servral seconds .so ,did we had some func to improve the performance?such like combine some small texture to a big.

# and another request!!!!!

recently unity4 is support a dynamic font ,and some people could use it in ngui. but a multi language font.ttf is too large(like some chinese font or your japanese font),do you have some time to see it ?if it could use sysfont instead of ttf.

**Comment by imkira** [comment]
That is out of the scope of unity-sysfont. unity-sysfont is a text to bitmap rendering-based plugin, it is not a glyph rendering-based plugin, so sorry I can't do that.
