### ISSUE TITLE
ime support??

### ISSUE THREAD

**Issue by xiqingdubu** [imkira/unity-sysfont#9]
can u supprt ime? just like UIInput in NGUI? thx

**Comment by imkira** [comment]
That would be an extension to NGUI compatibility package.
NGUI is (or at least was in 2.x, I haven't touched 3.x much) in fact very difficult to extend properly without changing NGUI's source code, and it is also very difficult to make a general solution that appeals everyone, therefore I don't have plans on adding that.
Let me know if you come up with something.
